### ISSUE TITLE
is this pack.osc up to date?

### ISSUE THREAD

**Issue by eps696** [elliotwoods/VVVV.Packs.OSC#1]
tried to download and compile this pack, but got an error 
NuGet Package restore failed for project VVVV.Packs.OSC: Unable to find version '2.5.0' of package 'System.ComponentModel.Composition.Codeplex'..

any clue/advice what am i doing wrong?
would really like to try these instead of "standard" vvvv osc en/decoders

**Comment by elliotwoods** [comment]
To be honest, I always have issues with NuGet

Just remove the references which it complains about
then add them again from either NuGet or from the DLL's in your VVVV `lib\core` folder

Suggest using the DLL's directly to get it building, and then if you feel more advanterous, try and switch over to NuGet

**Comment by eps696** [comment]
tried to install all references manually,
but now it asks for .nuget\NuGet.targets file
so stuck again..

---

eps

**Comment by eps696** [comment]
okk, fixed
just deleted requirements from csproj and it compiled ok
(also changed plugininterface version to 32.0.0)

---

eps

**Comment by elliotwoods** [comment]
Great to hear
Do you want to pull your changes?

**Comment by eps696** [comment]
ok, did my best to do that ::]
didn't manage to master any git skills yet, hopefully it's done properly
otherwise can just send you zip file

---

eps
